// REDUCER CONSTANTS
export const GIPHY_FETCHING = "GIPHY_FETCHING";
export const GIPHY_FETCHED = "GIPHY_FETCHED";
export const GIPHY_ERROR = "GIPHY_ERROR";
export const GIPHY_START_FETCH = "GIPHY_START_FETCH";
export const GIPHY_SEARCH_STRING = "GIPHY_SEARCH_STRING";
export const GIPHY_FETCH_NEXT = "GIPHY_FETCH_NEXT";

// GIPHY SERVICE CONSTANTS
export const GIPHY_API_KEY = "";
export const GIPHY_LIMIT = 25;

// ERROR MESSAGE CONSTANTS
export const GIPHY_ERROR_MESSAGE = "GIPHY Server not responding.";
